### ISSUE TITLE
Look into Gleditsh's datasets on distances for qStates

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qStates#10]
Look into whether the Minimum Distance Data (http://ksgleditsch.com/mindist.html) and Distance between Capital Cities (http://ksgleditsch.com/data-5.html) could/should be added to the qStates package.

**Comment by BBieri** [comment]
Will work to include the newer C-Shapes 2.0 dataset as this dataset builds upon and extends the precited datasets.

**Comment by BBieri** [comment]
We have decided to wait for the release of the CShapes 2.0 package before integrating it into `{qStates}`.

**Comment by BBieri** [comment]
[CShapes 2.0](https://cran.r-project.org/web/packages/cshapes/cshapes.pdf) launched about two weeks ago! Will integrate it soon as part of our new distances database.
